// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtbDGQmLrvK7vq17ivnHESSPf_idyacGs',
    appId: '1:450566981126:web:3d6e8c48e02d46029d6587',
    messagingSenderId: '450566981126',
    projectId: 'bazar-app-84b21',
    authDomain: 'bazar-app-84b21.firebaseapp.com',
    storageBucket: 'bazar-app-84b21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5SQsHf8M-rM2hhR_c5vQO-kmJvNFqGss',
    appId: '1:450566981126:android:986157c800427d409d6587',
    messagingSenderId: '450566981126',
    projectId: 'bazar-app-84b21',
    storageBucket: 'bazar-app-84b21.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKMxnGa9H8-D4FlnzqHt0LjTrOskadKys',
    appId: '1:450566981126:ios:d54b46f718ea3f839d6587',
    messagingSenderId: '450566981126',
    projectId: 'bazar-app-84b21',
    storageBucket: 'bazar-app-84b21.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtbDGQmLrvK7vq17ivnHESSPf_idyacGs',
    appId: '1:450566981126:web:db869988789f28e19d6587',
    messagingSenderId: '450566981126',
    projectId: 'bazar-app-84b21',
    authDomain: 'bazar-app-84b21.firebaseapp.com',
    storageBucket: 'bazar-app-84b21.firebasestorage.app',
  );
}
